version: '3'

services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
      # Uncomment and set your API key for production
      # - OPENAI_API_KEY=your_api_key_here
    volumes:
      # Mount .env file if available
      - ./.env:/app/.env:ro
    restart: unless-stopped 